package org.jboss.examples.conferences.domain;

// Generated Oct 31, 2014 3:44:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Speaker generated by hbm2java
 */
@Entity
@Table(name = "SPEAKER", schema = "PUBLIC", catalog = "CONFERENCES")
public class Speaker implements java.io.Serializable {

	private long id;
	private Integer version;
	private String bio;
	private String name;
	private String twitterhandle;
	private Set<Session> sessions = new HashSet<Session>(0);

	public Speaker() {
	}

	public Speaker(long id) {
		this.id = id;
	}

	public Speaker(long id, String bio, String name, String twitterhandle,
			Set<Session> sessions) {
		this.id = id;
		this.bio = bio;
		this.name = name;
		this.twitterhandle = twitterhandle;
		this.sessions = sessions;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "BIO")
	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TWITTERHANDLE")
	public String getTwitterhandle() {
		return this.twitterhandle;
	}

	public void setTwitterhandle(String twitterhandle) {
		this.twitterhandle = twitterhandle;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "SESSION_SPEAKER", schema = "PUBLIC", catalog = "CONFERENCES", joinColumns = { @JoinColumn(name = "SPEAKERS_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "SESSION_ID", nullable = false, updatable = false) })
	public Set<Session> getSessions() {
		return this.sessions;
	}

	public void setSessions(Set<Session> sessions) {
		this.sessions = sessions;
	}

}
